[project]
name = "book-recommender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.68.2",
    "streamlit>=1.43.2",
    "watchdog>=6.0.0",
]
